# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: windows-latest

variables:
  buildConfiguration: 'Release'
  dotnetVersion: '8.0.x'
  solution: 'src/TheUltimatePrompt/TheUltimatePrompt.sln'
  buildArtifactName: 'drop'
  
steps:
- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    version: '$(dotnetVersion)'
  displayName: 'Use .NET 8 SDK'

- task: NuGetToolInstaller@1
  displayName: 'Install NuGet'

- task: NuGetCommand@2
  inputs:
    restoreSolution: $(solution)
  displayName: 'Restore NuGet packages'

- script: |
    dotnet build $(solution) --configuration $(buildConfiguration) --no-restore
  displayName: 'Build solution'

- script: |
    dotnet test src/TheUltimatePrompt/UnitTests/UnitTests.csproj --configuration $(buildConfiguration) --no-build --verbosity normal --collect "Code coverage"
  displayName: 'Run unit tests'

- task: PublishTestResults@2
  inputs:
    testRunner: VSTest
    testResultsFiles: '**/*.trx'

- script: |
    dotnet test src/TheUltimatePrompt/IntegrationTests/IntegrationTests.csproj --configuration $(buildConfiguration) --no-build --verbosity normal
  displayName: 'Run integration tests'
  condition: 
 
